//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JITEF.DIME2Barcode
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICMaterialPicking
    {
        public string FID { get; set; }
        public string FSrcID { get; set; }
        public int FEntryID { get; set; }
        public Nullable<int> FItemID { get; set; }
        public Nullable<int> FUnitID { get; set; }
        public string FBatchNo { get; set; }
        public Nullable<decimal> FAuxQty { get; set; }
        public string FBiller { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FNote { get; set; }
    }
}
