//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JITEF.DIME2Barcode
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICMOInspectBill
    {
        public string FID { get; set; }
        public Nullable<int> FMOInterID { get; set; }
        public string FBillNo { get; set; }
        public int FTranType { get; set; }
        public int FStatus { get; set; }
        public Nullable<int> FOperID { get; set; }
        public Nullable<int> FWorkcenterID { get; set; }
        public Nullable<int> FMachineID { get; set; }
        public Nullable<decimal> FAuxQty { get; set; }
        public Nullable<decimal> FCheckAuxQty { get; set; }
        public Nullable<decimal> FPassAuxQty { get; set; }
        public Nullable<decimal> FFailAuxQty { get; set; }
        public Nullable<decimal> FFailAuxQtyP { get; set; }
        public Nullable<decimal> FFailAuxQtyM { get; set; }
        public Nullable<decimal> FPassAuxQtyP { get; set; }
        public Nullable<decimal> FPassAuxQtyM { get; set; }
        public string FNote { get; set; }
        public string FWorker { get; set; }
        public string FInspector { get; set; }
        public Nullable<System.DateTime> FInspectTime { get; set; }
        public string FBiller { get; set; }
        public Nullable<System.DateTime> FBillTime { get; set; }
        public string FChecker { get; set; }
        public Nullable<System.DateTime> FCheckTime { get; set; }
    }
}
