//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JITEF.DIME2Barcode
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PrintTemplate
    {
        public string FInterID { get; set; }
        public Nullable<int> FUserID { get; set; }
        public int FTranType { get; set; }
        public string FType { get; set; }
        public int FItemID { get; set; }
        public string FFileDir { get; set; }
        public byte[] FFile { get; set; }
        public string FNote { get; set; }
    }
}
