//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JITEF.DIME2Barcode
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MOInspectBillList
    {
        public string 检验单号 { get; set; }
        public string 派工单号 { get; set; }
        public string 生产任务 { get; set; }
        public string 状态 { get; set; }
        public System.DateTime 生产日期 { get; set; }
        public Nullable<System.DateTime> 汇报时间 { get; set; }
        public string 工作中心 { get; set; }
        public string 设备 { get; set; }
        public string 工序 { get; set; }
        public Nullable<decimal> 汇报数量 { get; set; }
        public Nullable<decimal> 检验数量 { get; set; }
        public Nullable<decimal> 合格数量 { get; set; }
        public Nullable<decimal> 不合格数量 { get; set; }
        public string 检验员 { get; set; }
        public Nullable<System.DateTime> 检验时间 { get; set; }
        public string FID { get; set; }
        public int FStatus { get; set; }
    }
}
